robot_arm:

  joint_state_controller:
    type : "joint_state_controller/JointStateController"
    publish_rate : 50

  joint_1_pos_controller:
    type : position_controllers/JointPositionController
    joint : arm_01_joint
    pid : { p: 100, i: 0.0, d: 10}
    gainn : 0.1

  joint_2_pos_controller:
    type : position_controllers/JointPositionController
    joint : arm_02_joint
    pid : { p: 100, i: 0.0, d: 10}
    gainn : 0.1

  arm_controller:
    type : position_controllers/JointTrajectoryController
    joints : 
      - arm_01_joint
      - arm_02_joint
